## NUMPY start:

- python for numbers

- numpy is a collection of functions related to numbers in python.

## array: 

- array is a data structure which consist of similar kind of datatype in multiple dimention

In [3]:
import numpy as np

In [21]:
ar1 = np.random.randint(1 ,5, 7)


In [22]:
ar1

array([3, 1, 2, 1, 2, 1, 3])

In [27]:
ar1.dtype  ##element datatype

dtype('int32')

In [28]:
type(ar1) ##structure

numpy.ndarray

In [29]:
np.ndim(ar1)  ##dimention of array

1

In [30]:
ar2 = np.random.randint(1 ,10, (5,5))

In [32]:
ar2

array([[4, 1, 6, 4, 5],
       [6, 5, 7, 4, 5],
       [5, 4, 8, 9, 5],
       [9, 6, 1, 2, 7],
       [2, 2, 1, 1, 6]])

In [33]:
np.ndim(ar2) ##dimention

2

In [35]:
ar2.shape ##row,column

(5, 5)

In [38]:
ar3 = np.random.randint(1 ,8, (4,5))

In [39]:
ar3.shape

(4, 5)

In [40]:
ar3

array([[1, 1, 3, 3, 7],
       [6, 1, 1, 7, 2],
       [1, 6, 5, 1, 6],
       [6, 7, 5, 3, 3]])

In [7]:
ar4 = np.arange(1,10)

In [45]:
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
ar4.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
ar4.shape

(9,)

In [5]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
ar5 = np.arange(51,100).reshape(7,7)

In [11]:
ar5

array([[51, 52, 53, 54, 55, 56, 57],
       [58, 59, 60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69, 70, 71],
       [72, 73, 74, 75, 76, 77, 78],
       [79, 80, 81, 82, 83, 84, 85],
       [86, 87, 88, 89, 90, 91, 92],
       [93, 94, 95, 96, 97, 98, 99]])

In [12]:
ar5[1:6]

array([[58, 59, 60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69, 70, 71],
       [72, 73, 74, 75, 76, 77, 78],
       [79, 80, 81, 82, 83, 84, 85],
       [86, 87, 88, 89, 90, 91, 92]])

In [14]:
#   [65, 66, 67, 68, 69, 70, 71]
#    [72, 73, 74, 75, 76, 77, 78]
#   [79, 80, 81, 82, 83, 84, 85]
ar5[2:5]

array([[65, 66, 67, 68, 69, 70, 71],
       [72, 73, 74, 75, 76, 77, 78],
       [79, 80, 81, 82, 83, 84, 85]])

In [15]:
# [86, 87, 88, 89, 90, 91, 92]
# [93, 94, 95, 96, 97, 98, 99]
ar5[5:]

array([[86, 87, 88, 89, 90, 91, 92],
       [93, 94, 95, 96, 97, 98, 99]])

In [17]:
ar5[:2]

array([[51, 52, 53, 54, 55, 56, 57],
       [58, 59, 60, 61, 62, 63, 64]])

In [18]:
ar5

array([[51, 52, 53, 54, 55, 56, 57],
       [58, 59, 60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69, 70, 71],
       [72, 73, 74, 75, 76, 77, 78],
       [79, 80, 81, 82, 83, 84, 85],
       [86, 87, 88, 89, 90, 91, 92],
       [93, 94, 95, 96, 97, 98, 99]])

In [20]:
# column:
# 2nd, 3rd, 4th, 5th column
ar5[:,1:5]

array([[52, 53, 54, 55],
       [59, 60, 61, 62],
       [66, 67, 68, 69],
       [73, 74, 75, 76],
       [80, 81, 82, 83],
       [87, 88, 89, 90],
       [94, 95, 96, 97]])

In [21]:
ar5[:,:2]

array([[51, 52],
       [58, 59],
       [65, 66],
       [72, 73],
       [79, 80],
       [86, 87],
       [93, 94]])

In [23]:
ar5[:,4:7]

array([[55, 56, 57],
       [62, 63, 64],
       [69, 70, 71],
       [76, 77, 78],
       [83, 84, 85],
       [90, 91, 92],
       [97, 98, 99]])

In [3]:
ar4 = np.arange(1,101).reshape(10,10)
ar4

NameError: name 'np' is not defined

In [26]:
# 3rd to 8th row

ar4[2:8]
#(0,1,2 index)

array([[21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
       [51, 52, 53, 54, 55, 56, 57, 58, 59, 60],
       [61, 62, 63, 64, 65, 66, 67, 68, 69, 70],
       [71, 72, 73, 74, 75, 76, 77, 78, 79, 80]])

In [28]:
# 3rd to 8th column

ar4[:, 2:8]

array([[ 3,  4,  5,  6,  7,  8],
       [13, 14, 15, 16, 17, 18],
       [23, 24, 25, 26, 27, 28],
       [33, 34, 35, 36, 37, 38],
       [43, 44, 45, 46, 47, 48],
       [53, 54, 55, 56, 57, 58],
       [63, 64, 65, 66, 67, 68],
       [73, 74, 75, 76, 77, 78],
       [83, 84, 85, 86, 87, 88],
       [93, 94, 95, 96, 97, 98]])

In [29]:
# [23, 24, 25, 26, 27, 28]
# [33, 34, 35, 36, 37, 38]
# [43, 44, 45, 46, 47, 48]
# [53, 54, 55, 56, 57, 58]
# [63, 64, 65, 66, 67, 68]
# [73, 74, 75, 76, 77, 78]

ar4[2:8, 2:8]

array([[23, 24, 25, 26, 27, 28],
       [33, 34, 35, 36, 37, 38],
       [43, 44, 45, 46, 47, 48],
       [53, 54, 55, 56, 57, 58],
       [63, 64, 65, 66, 67, 68],
       [73, 74, 75, 76, 77, 78]])

In [30]:
  # [55, 56, 57],
   #    [62, 63, 64],
   #    [69, 70, 71],
    #   [76, 77, 78]
ar5[5:8, 4:8] 

array([[90, 91, 92],
       [97, 98, 99]])

In [34]:
ar5[0:4, 4:8]

array([[55, 56, 57],
       [62, 63, 64],
       [69, 70, 71],
       [76, 77, 78]])

In [ ]:
# 42,  43,  44,  45,  46,  47
# 52,  53,  54,  55,  56,  57
#  62,  63,  64,  65,  66,  67,  68,  69,  70],
#  72,  73,  74,  75,  76,  77,  78,  79,  80],
# 82,  83,  84,  85,  86,  87,]
    


In [38]:
ar4[5:8, 2:5]

array([[53, 54, 55],
       [63, 64, 65],
       [73, 74, 75]])

In [41]:
# 4th 6th and 8th row
ar4[:,3:8:2]

array([[ 4,  6,  8],
       [14, 16, 18],
       [24, 26, 28],
       [34, 36, 38],
       [44, 46, 48],
       [54, 56, 58],
       [64, 66, 68],
       [74, 76, 78],
       [84, 86, 88],
       [94, 96, 98]])

In [42]:
# 4th 6th and 8th column:

ar4[:, 3:8:2]

array([[ 4,  6,  8],
       [14, 16, 18],
       [24, 26, 28],
       [34, 36, 38],
       [44, 46, 48],
       [54, 56, 58],
       [64, 66, 68],
       [74, 76, 78],
       [84, 86, 88],
       [94, 96, 98]])

In [46]:
# [14, 16, 18],
# [24, 26, 28],
# [34, 36, 38],
#[44, 46, 48],
#[54, 56, 58],
# [64, 66, 68],

ar4[1:6, 3:8:2]

array([[14, 16, 18],
       [24, 26, 28],
       [34, 36, 38],
       [44, 46, 48],
       [54, 56, 58]])

In [2]:
ar4

NameError: name 'ar4' is not defined

In [50]:
# [14, 16, 18], 
# [34, 36, 38],
# [54, 56, 58],

ar4[1:6:2, 3:8:2]


array([[14, 16, 18],
       [34, 36, 38],
       [54, 56, 58]])

In [51]:
#36,  38, 
# 56, 58,

ar4[3:6:2, 5:8:2]

array([[36, 38],
       [56, 58]])

In [52]:
# 2nd row and 7th row

ar4[1:8:5]

array([[11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [61, 62, 63, 64, 65, 66, 67, 68, 69, 70]])

In [53]:
ar4[[1,6]]

## second method

array([[11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [61, 62, 63, 64, 65, 66, 67, 68, 69, 70]])

In [55]:
# 5th column and 9th column

ar4[:, [5,8]]

array([[ 6,  9],
       [16, 19],
       [26, 29],
       [36, 39],
       [46, 49],
       [56, 59],
       [66, 69],
       [76, 79],
       [86, 89],
       [96, 99]])

# 7 FEB 2023

In [9]:
#array 5*6 starting from 101 - 136.
ar1 = np.arange(101,131).reshape(5,6)
ar1

array([[101, 102, 103, 104, 105, 106],
       [107, 108, 109, 110, 111, 112],
       [113, 114, 115, 116, 117, 118],
       [119, 120, 121, 122, 123, 124],
       [125, 126, 127, 128, 129, 130]])

In [10]:
# 107, 108, 109, 110, 111, 112],
#[113, 114, 115, 116, 117, 118],
#[119, 120, 121, 122, 123, 124],

ar1[1:4]

array([[107, 108, 109, 110, 111, 112],
       [113, 114, 115, 116, 117, 118],
       [119, 120, 121, 122, 123, 124]])

In [11]:
# 107, 108, 109, 110, 111, 112],
#[119, 120, 121, 122, 123, 124],

ar1[1:4:2]

array([[107, 108, 109, 110, 111, 112],
       [119, 120, 121, 122, 123, 124]])

In [13]:
#103, 104, 105, 106],
#109, 110, 111, 112],
#115, 116, 117, 118],
#121, 122, 123, 124],
ar1[:, 2:6]

array([[103, 104, 105, 106],
       [109, 110, 111, 112],
       [115, 116, 117, 118],
       [121, 122, 123, 124],
       [127, 128, 129, 130]])

In [14]:
# 103, 105
#121, 123
ar1[:4:3, 2:6:2]

array([[103, 105],
       [121, 123]])

In [15]:
ar1

array([[101, 102, 103, 104, 105, 106],
       [107, 108, 109, 110, 111, 112],
       [113, 114, 115, 116, 117, 118],
       [119, 120, 121, 122, 123, 124],
       [125, 126, 127, 128, 129, 130]])

In [16]:
ar1+100

array([[201, 202, 203, 204, 205, 206],
       [207, 208, 209, 210, 211, 212],
       [213, 214, 215, 216, 217, 218],
       [219, 220, 221, 222, 223, 224],
       [225, 226, 227, 228, 229, 230]])

In [17]:
ar1*10

array([[1010, 1020, 1030, 1040, 1050, 1060],
       [1070, 1080, 1090, 1100, 1110, 1120],
       [1130, 1140, 1150, 1160, 1170, 1180],
       [1190, 1200, 1210, 1220, 1230, 1240],
       [1250, 1260, 1270, 1280, 1290, 1300]])

In [18]:
ar1.shape

(5, 6)

In [19]:
ar2 = np.arange(1, 26).reshape(5,5)

In [20]:
ar2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [21]:
np.dot(ar2, ar2)

array([[ 215,  230,  245,  260,  275],
       [ 490,  530,  570,  610,  650],
       [ 765,  830,  895,  960, 1025],
       [1040, 1130, 1220, 1310, 1400],
       [1315, 1430, 1545, 1660, 1775]])

In [23]:
ar2@ar2

array([[ 215,  230,  245,  260,  275],
       [ 490,  530,  570,  610,  650],
       [ 765,  830,  895,  960, 1025],
       [1040, 1130, 1220, 1310, 1400],
       [1315, 1430, 1545, 1660, 1775]])

In [25]:
ar2+ar2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40],
       [42, 44, 46, 48, 50]])

In [26]:
np.eye(5,5) ## identical matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [28]:
ar2.T

array([[ 1,  6, 11, 16, 21],
       [ 2,  7, 12, 17, 22],
       [ 3,  8, 13, 18, 23],
       [ 4,  9, 14, 19, 24],
       [ 5, 10, 15, 20, 25]])

# Pandas:

In [2]:
import pandas as pd

In [34]:
pd.Series([23,45,65,75,75,57,76,45,75,7,56])

0     23
1     45
2     65
3     75
4     75
5     57
6     76
7     45
8     75
9      7
10    56
dtype: int64

diff between series and list:
 sereis is a data structure which contains diff types of datatypes in one dimention 
 and in series index and associated with by default each element
    

In [36]:
l1 = [32,43,45,43,3,2,233]

In [38]:
pd.Series([l1])

0    [32, 43, 45, 43, 3, 2, 233]
dtype: object

In [40]:
pd.Series(l1)

0     32
1     43
2     45
3     43
4      3
5      2
6    233
dtype: int64

In [43]:
## 10 random numbers:
pd.Series(np.random.randint(10,100,10))


0    94
1    77
2    84
3    19
4    22
5    23
6    16
7    42
8    89
9    84
dtype: int32

In [47]:
s1= pd.Series([10,20,30.40,50,60,70,80,90,100])

In [49]:
s1.shape

(9,)

In [50]:
type(s1)

pandas.core.series.Series

In [51]:
s1.dtype

dtype('float64')

In [52]:
s1= pd.Series([10,20,30.40,50,60,70,80,90,100],
              index=['A','B','c','D','E','F','G','I','J'])

In [54]:
s1

A     10.0
B     20.0
c     30.4
D     50.0
E     60.0
F     70.0
G     80.0
I     90.0
J    100.0
dtype: float64

In [58]:
pd.Series([23, 43, 34.33, 324.23, 'PYTHON', 'TANUJ', True, False], 
          index = list('ABCDEFGH'))

## we can strore differnt datatypoes in series

A        23
B        43
C     34.33
D    324.23
E    PYTHON
F     TANUJ
G      True
H     False
dtype: object

In [59]:
pd.Series([23, 43, 34.33, 324.23, 'PYTHON', 'TANUJ', True, False], 
          index = [23, 43, 34.33, 324.23, 'PYTHON', 'TANUJ', True, False])

23            23
43            43
34.33      34.33
324.23    324.23
PYTHON    PYTHON
TANUJ      TANUJ
True        True
False      False
dtype: object

In [62]:
s2 = pd.Series({"Apple":250, "Banana":30,"Kiwi":25,"orange":10,"Grapes":200})

In [63]:
s2

Apple     250
Banana     30
Kiwi       25
orange     10
Grapes    200
dtype: int64

In [70]:
s2 = pd.Series(np.arange(11,21), list('abcdefghij'))

In [71]:
s2

a    11
b    12
c    13
d    14
e    15
f    16
g    17
h    18
i    19
j    20
dtype: int32

In [72]:
# 13--18

s2[2:8]


c    13
d    14
e    15
f    16
g    17
h    18
dtype: int32

In [73]:
# e--y
s2['e':'y']

e    15
f    16
g    17
h    18
i    19
j    20
dtype: int32

In [74]:
s2['i':]

i    19
j    20
dtype: int32

In [79]:
s2

a    11
b    12
c    13
d    14
e    15
f    16
g    17
h    18
i    19
j    20
dtype: int32

In [80]:
s2>15

a    False
b    False
c    False
d    False
e    False
f     True
g     True
h     True
i     True
j     True
dtype: bool

In [81]:
s2[s2>15]

f    16
g    17
h    18
i    19
j    20
dtype: int32

In [82]:
s2<16

a     True
b     True
c     True
d     True
e     True
f    False
g    False
h    False
i    False
j    False
dtype: bool

In [84]:
s2[s2<16]

a    11
b    12
c    13
d    14
e    15
dtype: int32

In [85]:
s2+100

a    111
b    112
c    113
d    114
e    115
f    116
g    117
h    118
i    119
j    120
dtype: int32

In [86]:
s2*10

a    110
b    120
c    130
d    140
e    150
f    160
g    170
h    180
i    190
j    200
dtype: int32

In [87]:
s2/10

a    1.1
b    1.2
c    1.3
d    1.4
e    1.5
f    1.6
g    1.7
h    1.8
i    1.9
j    2.0
dtype: float64

In [93]:
np.nan

nan

# 08 feb 2023¶

In [120]:
s3 = pd.Series([10, 20, np.nan, 53, np.nan, np.nan, 54, 100, np.nan])

In [121]:
s3

0     10.0
1     20.0
2      NaN
3     53.0
4      NaN
5      NaN
6     54.0
7    100.0
8      NaN
dtype: float64

In [97]:
s3.isnull()

0    False
1    False
2     True
3    False
4     True
5     True
6    False
7    False
8     True
dtype: bool

In [98]:
s3.notnull()

0     True
1     True
2    False
3     True
4    False
5    False
6     True
7     True
8    False
dtype: bool

In [104]:
s3.notnull().sum()  ## filled values.

5

In [105]:
s3.isnull().sum()  ## missing values.

4

In [106]:
s3.fillna(0)

0     10.0
1     20.0
2      0.0
3     53.0
4      0.0
5      0.0
6     54.0
7    100.0
8      0.0
dtype: float64

In [107]:
s3.mean()

47.4

In [108]:
s3.fillna(s3.mean())

0     10.0
1     20.0
2     47.4
3     53.0
4     47.4
5     47.4
6     54.0
7    100.0
8     47.4
dtype: float64

In [110]:
s3[[2]].fillna(0)

2    0.0
dtype: float64

In [127]:
s3[2] = s3[[2]].fillna(0)

In [128]:
s3

0     10.0
1     20.0
2      0.0
3     53.0
4      NaN
5      NaN
6     54.0
7    100.0
8      NaN
dtype: float64

In [130]:
s3.fillna(method = 'ffill')   ## forwordfill

0     10.0
1     20.0
2      0.0
3     53.0
4     53.0
5     53.0
6     54.0
7    100.0
8    100.0
dtype: float64

In [132]:
s3.fillna(method = 'bfill')  ##backword fill

0     10.0
1     20.0
2      0.0
3     53.0
4     54.0
5     54.0
6     54.0
7    100.0
8      NaN
dtype: float64

In [134]:
s4 = pd.Series(['k3g','pathan','tiger','inception'], index = [2,5,8,10])

In [135]:
s4

2           k3g
5        pathan
8         tiger
10    inception
dtype: object

In [138]:
s4.reindex(range(15), method = 'bfill')

0           k3g
1           k3g
2           k3g
3        pathan
4        pathan
5        pathan
6         tiger
7         tiger
8         tiger
9     inception
10    inception
11          NaN
12          NaN
13          NaN
14          NaN
dtype: object

In [139]:
s4.reindex(range(15), method = 'ffill')

0           NaN
1           NaN
2           k3g
3           k3g
4           k3g
5        pathan
6        pathan
7        pathan
8         tiger
9         tiger
10    inception
11    inception
12    inception
13    inception
14    inception
dtype: object

###  data frames: 
data frames are the data structure which collects different kind of data or diff type of data in respectives rows and column combinations. that is 2 dimentional.. it is mostly tabular form data.

In [142]:
df = pd.DataFrame(np.arange(1,26).reshape(5,5))

In [143]:
df

0   1   2   3   4
0   1   2   3   4   5
1   6   7   8   9  10
2  11  12  13  14  15
3  16  17  18  19  20
4  21  22  23  24  25

In [144]:
df.shape

(5, 5)

In [145]:
type(df)

pandas.core.frame.DataFrame

In [147]:
df = pd.DataFrame(np.arange(1,26).reshape(5,5), index = list("ABCDE"))

In [148]:
df

0   1   2   3   4
A   1   2   3   4   5
B   6   7   8   9  10
C  11  12  13  14  15
D  16  17  18  19  20
E  21  22  23  24  25

In [150]:
df = pd.DataFrame(np.arange(1,26).reshape(5,5), 
                  index = list("ABCDE"), columns = list("PQRST"))

In [151]:
df

P   Q   R   S   T
A   1   2   3   4   5
B   6   7   8   9  10
C  11  12  13  14  15
D  16  17  18  19  20
E  21  22  23  24  25

In [15]:
ar = np.arange(101,201).reshape(10,10)
index = ['A','B','C','D','E','F','G','H','I','J']
column = list("PQRSTUVWXY")

ab = pd.DataFrame(ar,index = index, columns = column)

In [16]:
ab

P    Q    R    S    T    U    V    W    X    Y
A  101  102  103  104  105  106  107  108  109  110
B  111  112  113  114  115  116  117  118  119  120
C  121  122  123  124  125  126  127  128  129  130
D  131  132  133  134  135  136  137  138  139  140
E  141  142  143  144  145  146  147  148  149  150
F  151  152  153  154  155  156  157  158  159  160
G  161  162  163  164  165  166  167  168  169  170
H  171  172  173  174  175  176  177  178  179  180
I  181  182  183  184  185  186  187  188  189  190
J  191  192  193  194  195  196  197  198  199  200

In [19]:
# 2nd to 6th row:

ab['B':'F']

P    Q    R    S    T    U    V    W    X    Y
B  111  112  113  114  115  116  117  118  119  120
C  121  122  123  124  125  126  127  128  129  130
D  131  132  133  134  135  136  137  138  139  140
E  141  142  143  144  145  146  147  148  149  150
F  151  152  153  154  155  156  157  158  159  160

In [23]:
ab[['Q','R']]

Q    R
A  102  103
B  112  113
C  122  123
D  132  133
E  142  143
F  152  153
G  162  163
H  172  173
I  182  183
J  192  193

In [24]:
ab.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, A to J
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   P       10 non-null     int32
 1   Q       10 non-null     int32
 2   R       10 non-null     int32
 3   S       10 non-null     int32
 4   T       10 non-null     int32
 5   U       10 non-null     int32
 6   V       10 non-null     int32
 7   W       10 non-null     int32
 8   X       10 non-null     int32
 9   Y       10 non-null     int32
dtypes: int32(10)
memory usage: 780.0+ bytes


In [25]:
ab.describe()

P           Q           R           S           T           U  \
count   10.000000   10.000000   10.000000   10.000000   10.000000   10.000000   
mean   146.000000  147.000000  148.000000  149.000000  150.000000  151.000000   
std     30.276504   30.276504   30.276504   30.276504   30.276504   30.276504   
min    101.000000  102.000000  103.000000  104.000000  105.000000  106.000000   
25%    123.500000  124.500000  125.500000  126.500000  127.500000  128.500000   
50%    146.000000  147.000000  148.000000  149.000000  150.000000  151.000000   
75%    168.500000  169.500000  170.500000  171.500000  172.500000  173.500000   
max    191.000000  192.000000  193.000000  194.000000  195.000000  196.000000   

                V           W           X           Y  
count   10.000000   10.000000   10.000000   10.000000  
mean   152.000000  153.000000  154.000000  155.000000  
std     30.276504   30.276504   30.276504   30.276504  
min    107.000000  108.000000  109.000000  110.000000  
25%    129.500000  130.500000  131.500000  132.500000  
50%    152.000000  153.000000  154.000000  155.000000  
75%    174.500000  175.500000  176.500000  177.500000  
max    197.000000  198.000000  199.000000  200.000000

In [27]:
ab.isnull().sum()

P    0
Q    0
R    0
S    0
T    0
U    0
V    0
W    0
X    0
Y    0
dtype: int64

In [29]:
d1 = { "fruits": ["apple","banana","kiwi","mango","orange","guava"],
     "price":[100,20,230,46,37,250]}


In [30]:
df1 = pd.DataFrame(d1)

In [31]:
df1

fruits  price
0   apple    100
1  banana     20
2    kiwi    230
3   mango     46
4  orange     37
5   guava    250

In [32]:
Q = [10,20,30,40,43,53]

In [35]:
df1['Quantity'] = Q

In [40]:
df1

fruits  price  quantity  Quantity
0   apple    100        10        10
1  banana     20        20        20
2    kiwi    230        30        30
3   mango     46        40        40
4  orange     37        43        43
5   guava    250        53        53

In [41]:
df1['Total price'] = df1['price'] * df1['Quantity']

In [42]:
df1

fruits  price  quantity  Quantity  Total price
0   apple    100        10        10         1000
1  banana     20        20        20          400
2    kiwi    230        30        30         6900
3   mango     46        40        40         1840
4  orange     37        43        43         1591
5   guava    250        53        53        13250

In [44]:
df1['Discount'] = [10,20,5,50,30,25]

In [45]:
df1 

fruits  price  quantity  Quantity  Total price  Discount
0   apple    100        10        10         1000        10
1  banana     20        20        20          400        20
2    kiwi    230        30        30         6900         5
3   mango     46        40        40         1840        50
4  orange     37        43        43         1591        30
5   guava    250        53        53        13250        25

In [47]:
df1['Final price'] = df1['Total price'] - ((df1['Total price'] * df1['Discount'])/100)

In [48]:
df1

fruits  price  quantity  Quantity  Total price  Discount  Final price
0   apple    100        10        10         1000        10        900.0
1  banana     20        20        20          400        20        320.0
2    kiwi    230        30        30         6900         5       6555.0
3   mango     46        40        40         1840        50        920.0
4  orange     37        43        43         1591        30       1113.7
5   guava    250        53        53        13250        25       9937.5

## 9 feb thrusday

In [53]:
import pandas as pd

In [32]:
tn = pd.DataFrame({'Company':[], 'stockprices':[]})

In [33]:
tn

Empty DataFrame
Columns: [Company, stockprices]
Index: []

In [34]:
company = ['TCS','Reliance','Wipro','Zomato','Nyka','Airtel']
sp = [1200, 2000, 212, 50, 154, 1544]

In [35]:
tn['Company'] = company

In [36]:
tn['stockprices'] = sp

In [37]:
tn

Company  stockprices
0       TCS         1200
1  Reliance         2000
2     Wipro          212
3    Zomato           50
4      Nyka          154
5    Airtel         1544

In [38]:
tn['stock count'] = [187,515,6164,24,644,464]

In [41]:
tn['Total value'] = tn['stockprices']*tn['stock count']

In [42]:
tn

Company  stockprices  stock count  Total value
0       TCS         1200          187       224400
1  Reliance         2000          515      1030000
2     Wipro          212         6164      1306768
3    Zomato           50           24         1200
4      Nyka          154          644        99176
5    Airtel         1544          464       716416

In [44]:
import numpy as np

In [57]:
from pandas import DataFrame as dff

In [68]:
df = dff({'product':['Tea', 'coffee', np.nan, 'Rice', 'Beans', 'Almond', np.nan, 'facewash', 'Shampoo', 'Sugar'],
       'price':[100, 200, np.nan, np.nan, 450, np.nan, 700, 300, np.nan, 200],
       'quantity':[10, 20, np.nan, np.nan, np.nan, 10, 5, np.nan, 60, 30]})


In [69]:
df

product  price  quantity
0       Tea  100.0      10.0
1    coffee  200.0      20.0
2       NaN    NaN       NaN
3      Rice    NaN       NaN
4     Beans  450.0       NaN
5    Almond    NaN      10.0
6       NaN  700.0       5.0
7  facewash  300.0       NaN
8   Shampoo    NaN      60.0
9     Sugar  200.0      30.0

In [70]:
df.isnull().sum()

product     2
price       4
quantity    4
dtype: int64

In [71]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   product   8 non-null      object 
 1   price     6 non-null      float64
 2   quantity  6 non-null      float64
dtypes: float64(2), object(1)
memory usage: 368.0+ bytes


In [94]:
df['product'] = df['product'].fillna("Others")

In [95]:
df

product  price  quantity
0       Tea  100.0      10.0
1    coffee  200.0      20.0
2    Others  325.0      22.5
3      Rice  325.0      22.5
4     Beans  450.0      22.5
5    Almond  325.0      10.0
6    Others  700.0       5.0
7  facewash  300.0      22.5
8   Shampoo  325.0      60.0
9     Sugar  200.0      30.0

In [96]:
df.price

0    100.0
1    200.0
2    325.0
3    325.0
4    450.0
5    325.0
6    700.0
7    300.0
8    325.0
9    200.0
Name: price, dtype: float64

In [97]:
df.price.mean()   ## avg value

325.0

In [98]:
df.price = df.price.fillna(df.price.mean())

In [99]:
df

product  price  quantity
0       Tea  100.0      10.0
1    coffee  200.0      20.0
2    Others  325.0      22.5
3      Rice  325.0      22.5
4     Beans  450.0      22.5
5    Almond  325.0      10.0
6    Others  700.0       5.0
7  facewash  300.0      22.5
8   Shampoo  325.0      60.0
9     Sugar  200.0      30.0

In [100]:
df.quantity

0    10.0
1    20.0
2    22.5
3    22.5
4    22.5
5    10.0
6     5.0
7    22.5
8    60.0
9    30.0
Name: quantity, dtype: float64

In [101]:
df.quantity.mode()

0    22.5
Name: quantity, dtype: float64

In [102]:
df.quantity = df.quantity.fillna(df.quantity.mode())

In [103]:
df

product  price  quantity
0       Tea  100.0      10.0
1    coffee  200.0      20.0
2    Others  325.0      22.5
3      Rice  325.0      22.5
4     Beans  450.0      22.5
5    Almond  325.0      10.0
6    Others  700.0       5.0
7  facewash  300.0      22.5
8   Shampoo  325.0      60.0
9     Sugar  200.0      30.0

In [108]:
df.price>300

0    False
1    False
2     True
3     True
4     True
5     True
6     True
7    False
8     True
9    False
Name: price, dtype: bool

In [107]:
df[df.price>300]

product  price  quantity
2   Others  325.0      22.5
3     Rice  325.0      22.5
4    Beans  450.0      22.5
5   Almond  325.0      10.0
6   Others  700.0       5.0
8  Shampoo  325.0      60.0

In [109]:
df[df.quantity>20]

product  price  quantity
2    Others  325.0      22.5
3      Rice  325.0      22.5
4     Beans  450.0      22.5
7  facewash  300.0      22.5
8   Shampoo  325.0      60.0
9     Sugar  200.0      30.0

# 13 feb monday

In [32]:
import numpy as np

In [33]:
import pandas as pd

In [52]:
city = ['Gujrat', 'delhi', 'Noida', 'Agra','Dehradun', 'Pune', 'chennai','Bangluru']
income = [40000,30000,60000, np.nan, 5600000, np.nan, 67000, np.nan]


In [53]:
df = pd.DataFrame()

In [54]:
df

Empty DataFrame
Columns: []
Index: []

In [55]:
df['City'] = city
df['income'] = income

In [56]:
df

City     income
0    Gujrat    40000.0
1     delhi    30000.0
2     Noida    60000.0
3      Agra        NaN
4  Dehradun  5600000.0
5      Pune        NaN
6   chennai    67000.0
7  Bangluru        NaN

In [57]:
df.isnull().sum()

City      0
income    3
dtype: int64

In [58]:
df['income'].mean()

1159400.0

In [59]:
df['income'] = df['income'].fillna(df['income'].mean())

In [60]:
df

City     income
0    Gujrat    40000.0
1     delhi    30000.0
2     Noida    60000.0
3      Agra  1159400.0
4  Dehradun  5600000.0
5      Pune  1159400.0
6   chennai    67000.0
7  Bangluru  1159400.0

In [61]:
df.income.mean()

1159400.0

In [63]:
df[df.income > df.income.mean()]

City     income
4  Dehradun  5600000.0

In [64]:
df

City     income
0    Gujrat    40000.0
1     delhi    30000.0
2     Noida    60000.0
3      Agra  1159400.0
4  Dehradun  5600000.0
5      Pune  1159400.0
6   chennai    67000.0
7  Bangluru  1159400.0

In [77]:
state = ['Hariyana','Delhi','U.P','U.P','Uttarakhand','Maharastra','Tamilnadu','A.P']

In [78]:
df['state'] = state

In [79]:
df['Zip code'] = np.random.randint(40000, 49999,8)

In [80]:
df

City     income        state  Zip code  Population
0    Gujrat    40000.0     Hariyana     47341      650139
1     delhi    30000.0        Delhi     41475      719605
2     Noida    60000.0          U.P     42039      916232
3      Agra  1159400.0          U.P     46784      771095
4  Dehradun  5600000.0  Uttarakhand     41823      916130
5      Pune  1159400.0   Maharastra     44739      954721
6   chennai    67000.0    Tamilnadu     44380      642194
7  Bangluru  1159400.0          A.P     49109      856849

In [81]:
df['Population'] = np.random.randint(600000,1000000, 8)

In [82]:
df

City     income        state  Zip code  Population
0    Gujrat    40000.0     Hariyana     47341      906399
1     delhi    30000.0        Delhi     41475      638686
2     Noida    60000.0          U.P     42039      742384
3      Agra  1159400.0          U.P     46784      984409
4  Dehradun  5600000.0  Uttarakhand     41823      941887
5      Pune  1159400.0   Maharastra     44739      956153
6   chennai    67000.0    Tamilnadu     44380      829236
7  Bangluru  1159400.0          A.P     49109      668632

In [83]:
df[df['state'] == 'U.P']

City     income state  Zip code  Population
2  Noida    60000.0   U.P     42039      742384
3   Agra  1159400.0   U.P     46784      984409

## .iloc()

In [84]:
df

City     income        state  Zip code  Population
0    Gujrat    40000.0     Hariyana     47341      906399
1     delhi    30000.0        Delhi     41475      638686
2     Noida    60000.0          U.P     42039      742384
3      Agra  1159400.0          U.P     46784      984409
4  Dehradun  5600000.0  Uttarakhand     41823      941887
5      Pune  1159400.0   Maharastra     44739      956153
6   chennai    67000.0    Tamilnadu     44380      829236
7  Bangluru  1159400.0          A.P     49109      668632

In [85]:
df.shape

(8, 5)

In [86]:
df.iloc[1:6]

City     income        state  Zip code  Population
1     delhi    30000.0        Delhi     41475      638686
2     Noida    60000.0          U.P     42039      742384
3      Agra  1159400.0          U.P     46784      984409
4  Dehradun  5600000.0  Uttarakhand     41823      941887
5      Pune  1159400.0   Maharastra     44739      956153

In [87]:
df.iloc[5:,]

City     income       state  Zip code  Population
5      Pune  1159400.0  Maharastra     44739      956153
6   chennai    67000.0   Tamilnadu     44380      829236
7  Bangluru  1159400.0         A.P     49109      668632

In [91]:
df.iloc[:5]

City     income        state  Zip code  Population
0    Gujrat    40000.0     Hariyana     47341      906399
1     delhi    30000.0        Delhi     41475      638686
2     Noida    60000.0          U.P     42039      742384
3      Agra  1159400.0          U.P     46784      984409
4  Dehradun  5600000.0  Uttarakhand     41823      941887

In [93]:
df.iloc[:,0:3]

City     income        state
0    Gujrat    40000.0     Hariyana
1     delhi    30000.0        Delhi
2     Noida    60000.0          U.P
3      Agra  1159400.0          U.P
4  Dehradun  5600000.0  Uttarakhand
5      Pune  1159400.0   Maharastra
6   chennai    67000.0    Tamilnadu
7  Bangluru  1159400.0          A.P

In [94]:
df.iloc[:, 1:4]

income        state  Zip code
0    40000.0     Hariyana     47341
1    30000.0        Delhi     41475
2    60000.0          U.P     42039
3  1159400.0          U.P     46784
4  5600000.0  Uttarakhand     41823
5  1159400.0   Maharastra     44739
6    67000.0    Tamilnadu     44380
7  1159400.0          A.P     49109

In [95]:
df.iloc[:, [1,4]]

income  Population
0    40000.0      906399
1    30000.0      638686
2    60000.0      742384
3  1159400.0      984409
4  5600000.0      941887
5  1159400.0      956153
6    67000.0      829236
7  1159400.0      668632

In [96]:
df.iloc[:, [0,2]]

City        state
0    Gujrat     Hariyana
1     delhi        Delhi
2     Noida          U.P
3      Agra          U.P
4  Dehradun  Uttarakhand
5      Pune   Maharastra
6   chennai    Tamilnadu
7  Bangluru          A.P

In [97]:
df.iloc[0:4, [0,2]]

City     state
0  Gujrat  Hariyana
1   delhi     Delhi
2   Noida       U.P
3    Agra       U.P

In [98]:
df.iloc[[1,7], [0,4]]

City  Population
1     delhi      638686
7  Bangluru      668632

In [100]:
df

City     income        state  Zip code  Population
0    Gujrat    40000.0     Hariyana     47341      906399
1     delhi    30000.0        Delhi     41475      638686
2     Noida    60000.0          U.P     42039      742384
3      Agra  1159400.0          U.P     46784      984409
4  Dehradun  5600000.0  Uttarakhand     41823      941887
5      Pune  1159400.0   Maharastra     44739      956153
6   chennai    67000.0    Tamilnadu     44380      829236
7  Bangluru  1159400.0          A.P     49109      668632

In [102]:
df.index = list("ABCDEFGH")

In [103]:
df

City     income        state  Zip code  Population
A    Gujrat    40000.0     Hariyana     47341      906399
B     delhi    30000.0        Delhi     41475      638686
C     Noida    60000.0          U.P     42039      742384
D      Agra  1159400.0          U.P     46784      984409
E  Dehradun  5600000.0  Uttarakhand     41823      941887
F      Pune  1159400.0   Maharastra     44739      956153
G   chennai    67000.0    Tamilnadu     44380      829236
H  Bangluru  1159400.0          A.P     49109      668632

In [104]:
df.index

Index(['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H'], dtype='object')

In [106]:
df.columns

Index(['City', 'income', 'state', 'Zip code', 'Population'], dtype='object')

In [112]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8 entries, A to H
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   City        8 non-null      object 
 1   income      8 non-null      float64
 2   state       8 non-null      object 
 3   Zip code    8 non-null      object 
 4   Population  8 non-null      int32  
dtypes: float64(1), int32(1), object(3)
memory usage: 652.0+ bytes


In [110]:
df['Zip code'] = df['Zip code'].astype("str")

In [111]:
df.describe()

income     Population
count  8.000000e+00       8.000000
mean   1.159400e+06  833473.250000
std    1.876530e+06  135400.751268
min    3.000000e+04  638686.000000
25%    5.500000e+04  723946.000000
50%    6.132000e+05  867817.500000
75%    1.159400e+06  945453.500000
max    5.600000e+06  984409.000000

In [113]:
df

City     income        state Zip code  Population
A    Gujrat    40000.0     Hariyana    47341      906399
B     delhi    30000.0        Delhi    41475      638686
C     Noida    60000.0          U.P    42039      742384
D      Agra  1159400.0          U.P    46784      984409
E  Dehradun  5600000.0  Uttarakhand    41823      941887
F      Pune  1159400.0   Maharastra    44739      956153
G   chennai    67000.0    Tamilnadu    44380      829236
H  Bangluru  1159400.0          A.P    49109      668632

### .loc:

In [114]:
df

City     income        state Zip code  Population
A    Gujrat    40000.0     Hariyana    47341      906399
B     delhi    30000.0        Delhi    41475      638686
C     Noida    60000.0          U.P    42039      742384
D      Agra  1159400.0          U.P    46784      984409
E  Dehradun  5600000.0  Uttarakhand    41823      941887
F      Pune  1159400.0   Maharastra    44739      956153
G   chennai    67000.0    Tamilnadu    44380      829236
H  Bangluru  1159400.0          A.P    49109      668632

In [118]:
df.loc['B':'E']

City     income        state Zip code  Population
B     delhi    30000.0        Delhi    41475      638686
C     Noida    60000.0          U.P    42039      742384
D      Agra  1159400.0          U.P    46784      984409
E  Dehradun  5600000.0  Uttarakhand    41823      941887

In [119]:
df.loc[['B','E']]

City     income        state Zip code  Population
B     delhi    30000.0        Delhi    41475      638686
E  Dehradun  5600000.0  Uttarakhand    41823      941887

In [120]:
df.loc[['A','B','C']]

City   income     state Zip code  Population
A  Gujrat  40000.0  Hariyana    47341      906399
B   delhi  30000.0     Delhi    41475      638686
C   Noida  60000.0       U.P    42039      742384

In [124]:
df.loc[:, 'City': 'state']

City     income        state
A    Gujrat    40000.0     Hariyana
B     delhi    30000.0        Delhi
C     Noida    60000.0          U.P
D      Agra  1159400.0          U.P
E  Dehradun  5600000.0  Uttarakhand
F      Pune  1159400.0   Maharastra
G   chennai    67000.0    Tamilnadu
H  Bangluru  1159400.0          A.P

In [125]:
df.loc[:, ['City','Zip code']]

City Zip code
A    Gujrat    47341
B     delhi    41475
C     Noida    42039
D      Agra    46784
E  Dehradun    41823
F      Pune    44739
G   chennai    44380
H  Bangluru    49109

In [127]:
df.loc['A':'E', ['City','Zip code']]

City Zip code
A    Gujrat    47341
B     delhi    41475
C     Noida    42039
D      Agra    46784
E  Dehradun    41823

In [131]:
df.loc[['A','H'], ['state','Population']]

state  Population
A  Hariyana      906399
H       A.P      668632

In [133]:
df.iloc[[0,7], [2,4]]     ## using iloc

state  Population
A  Hariyana      906399
H       A.P      668632